#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This script reads files generated by the fitting scripts (xyz_fit.py) 
and writes the fitting parameters to a new file for further analysis. 

written by: Philip Groß, April 2020, GEO FU Berlin
philip.gross@fu-berlin.de
"""

# load packages:
#import sys
import os
import glob
import pandas as pd
from io import StringIO


##   -------------------------------------------------------------------   ##
## USER INPUT ##
# Specify the file location. You can also use wildcards!
#file_location = 'std_fit.txt'
file_location = './qz_fit.txt'
##   -------------------------------------------------------------------   ##

# initialize output file
with open('fitting_results.txt', 'w') as f_out:
    f_out.write('file_name' 
                + ' ' + 'sample_name' 
                + ' ' + 'peak_position' 
                + ' ' + 'fit_uncertainty' 
                + ' ' + '\n')

for file in list(glob.glob(file_location)):
    filename = os.path.basename(file)
    
    with open(file) as f:
        content = f.readlines()
    
    # parse file for peak parameters and convert the list to a string
    #peak_params = str(content[12:22])
    peak_params = str(content).split('[[Variables]]')[1].split('[[Correlations]]')[0][4:]
    #print(peak_params)

    
    # remove unwanted characters
    peak_params = peak_params.replace('+/-', '')
    peak_params = peak_params.replace(':', '')
    peak_params = peak_params.replace('init= ', '')
    peak_params = peak_params.replace('(', '')
    peak_params = peak_params.replace(')', '')
    peak_params = peak_params.replace('[', '')
    peak_params = peak_params.replace(']', '')
    peak_params = peak_params.replace('%', '')
    peak_params = peak_params.replace('\\n', ';')
    peak_params = peak_params.replace(',', '')
    
    # remove unwanted whitespace
    peak_params = ' '.join(peak_params.split())
    print(peak_params)
    
    # import data as dataframe
    df = pd.read_csv(StringIO(peak_params),
                     names=[' ','parameter','position','abs_error','rel_error','ini','n'],
                     #names=['parameter','position','abs_error','rel_error','ini','n'],
                     header=None,
                     lineterminator=';',#',',
                     index_col=None,
                     delimiter='\s+').drop(['ini','n'], axis=1).set_index('parameter')
    
    print(df)
    #df.loc['qz_center'].to_csv('fitting_results.txt', sep=' ', mode='w')
    
    # write data to file 
    with open('fitting_results.txt', 'a') as f_out:
        f_out.write(#filename
                    #+ ' ' + 
                    filename[:-21]
    #                + ' ' + str(df.loc['qz464_center'].loc['position'])
    #                + ' ' + str(df.loc['qz464_center'].loc['abs_error'])
                    + ' ' + str(df.loc['qz_center'].loc['position'])
                    + ' ' + str(df.loc['qz_center'].loc['abs_error'])
                    + ' ' + '\n')










##
